baseURL = '/'
languageCode = 'en-us'
title = 'Scrivener'
theme = "ace-documentation"
[[menu.shortcuts]]
name = "My GitHub <i class='fab fa-github'></i>"
url = "https://github.com/SingingFoot"
weight = 10
[params]
favicon = "img/favicon.ico" 